'use client'

import { useState } from 'react'
import { Download, Loader2 } from 'lucide-react'
import { Message, AIModel, PERSPECTIVES } from '@/types'
import { cn } from '@/lib/utils'

type ExportButtonProps = {
  messages: Message[]
  selectedModel: AIModel
  disabled?: boolean
}

export function ExportButton({ messages, selectedModel, disabled }: ExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false)

  const generatePDF = async () => {
    if (messages.length === 0) return

    setIsExporting(true)

    try {
      // Build conversation text for summary
      const conversationText = messages
        .map((m) => {
          const perspective = m.perspective
            ? PERSPECTIVES.find((p) => p.id === m.perspective)?.name
            : 'User'
          return `${perspective}: ${m.content}`
        })
        .join('\n\n')

      // Get AI-generated summary
      let summary = ''
      try {
        const summaryResponse = await fetch('/api/summary', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            conversation: conversationText,
            modelId: selectedModel.id,
          }),
        })
        const summaryData = await summaryResponse.json()
        summary = summaryData.summary || 'Summary could not be generated.'
      } catch {
        summary = 'Summary could not be generated.'
      }

      // Import jsPDF dynamically
      const { jsPDF } = await import('jspdf')

      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pageWidth = doc.internal.pageSize.getWidth()
      const pageHeight = doc.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - margin * 2
      let y = margin

      const addPage = () => {
        doc.addPage()
        y = margin
      }

      const writeText = (text: string, fontSize: number, isBold = false, color: [number, number, number] = [0, 0, 0]) => {
        doc.setFontSize(fontSize)
        doc.setTextColor(...color)
        doc.setFont('helvetica', isBold ? 'bold' : 'normal')

        const lines = doc.splitTextToSize(text, contentWidth)
        const lineHeight = fontSize * 0.4

        for (const line of lines) {
          if (y + lineHeight > pageHeight - margin) addPage()
          doc.text(line, margin, y)
          y += lineHeight
        }
      }

      // Header
      writeText('Nodiac Oracle', 20, true, [0, 102, 204])
      writeText('Multi-perspective AI Advisor', 11, false, [100, 100, 100])
      y += 5

      // Summary
      writeText('Summary', 12, true, [0, 102, 204])
      writeText(summary, 10, false, [50, 50, 50])
      y += 5

      // Meta info
      writeText(`Model: ${selectedModel.name} | Exported: ${new Date().toLocaleDateString()}`, 9, false, [120, 120, 120])
      y += 8

      // Conversation
      for (const message of messages) {
        const isUser = message.role === 'user'
        const perspective = message.perspective
          ? PERSPECTIVES.find((p) => p.id === message.perspective)
          : null

        const speaker = isUser ? 'You' : perspective?.name || 'Assistant'

        writeText(`${speaker}:`, 10, true, isUser ? [0, 102, 204] : [80, 80, 80])
        writeText(message.content, 10, false, [30, 30, 30])
        y += 4
      }

      // Footer
      if (y + 15 > pageHeight - margin) addPage()
      y = pageHeight - 15
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by Nodiac Oracle', pageWidth / 2, y, { align: 'center' })

      doc.save(`nodiac-oracle-${new Date().toISOString().split('T')[0]}.pdf`)
    } catch (error) {
      console.error('PDF export error:', error)
      alert('Failed to export PDF. Please try again.')
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <button
      onClick={generatePDF}
      disabled={disabled || isExporting || messages.length === 0}
      className={cn(
        'w-full flex items-center justify-center gap-2 px-4 py-2 rounded-lg text-sm',
        'bg-nodiac-primary text-white hover:bg-nodiac-primary/90',
        'disabled:opacity-50 disabled:cursor-not-allowed'
      )}
    >
      {isExporting ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Export PDF
        </>
      )}
    </button>
  )
}
